name: 'Inclusivelint Github Action'
description: 'Github action that finds non inclusive words on a repository'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
    icon: 'check'
    color: 'blue'