on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Action testing job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Test action step
        uses: ./
        id: test
      
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"